blank_issues_enabled: false
contact_links:
  - name: All Issues
    url: https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose
    about: For bug reports or feature requests, please see the parent GitHub repository of this Chart.
